name: Build SAP Commerce Extensions

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    # Usa a imagem SAP Commerce (Docker Hub privado)
    container:
      image: matheusbonnet/sap-commerce-ootb:latest
      credentials:
        username: matheusbonnet
        password: Mat09022002
    steps:
      # 1️⃣ Checkout do seu repositório (sua pasta custom)
      - name: Checkout repository
        uses: actions/checkout@v4
      # 2️⃣ Substitui a pasta custom dentro do container
      - name: Copy custom extensions
        run: |
          rm -rf /opt/hybris/bin/custom || true
          cp -r $GITHUB_WORKSPACE/hybris/bin/custom /opt/hybris/bin/custom
      # 3️⃣ Build das extensões
      - name: Build Extensions
        run: |
          cd /opt/hybris/bin/platform
          if [ -f ./setantenv.sh ]; then
            bash -c "source ./setantenv.sh && ant all"
          else
            # Para SCS / Maven build
            mvn clean install -Pproduction
          fi
